### ISSUE TITLE
Consider multi-writer transactions?

### ISSUE THREAD

**Issue by jeromegn** [arthurprs/canopydb#5]
Having just [implemented it in `fjall`](https://github.com/fjall-rs/fjall/pull/79), it's really not that bad in terms of added complexity.

Of course it depends on each database's snapshotting implementation and garbage collection, but I suspect it wouldn't be too hard to add in Canopy.

Most of the new code is in `src/tx/oracle.rs` and `src/tx/conflict_manager.rs`, roughly 300 lines of code.

It could be feature-flagged due to the added conflict error when committing.

**Comment by arthurprs** [comment]
I think it requires less code in an LSM because there's already machinery to merge the transaction memtable(s) with the rest of the snapshot. Adding such functionality to Canopy would be a significantly larger lift.

However, there might be a reasonable path to adding multi-writer transactions (w/o major code changes) by using page-level conflict detection (and/or locking).

**Comment by arthurprs** [comment]
Wait, that first paragraph is not really right...

It should be possible to have each concurrent write txn to operate on mutable (COW) version of the database (thus no merging machinery required). Then at commit time the write txn either replaces the main tree (if there was nothing commited in between) or replays the mutation on the main tree if there aren't conflicts.
